shuiju_zzsbb = ['return $("input[ng-model=\'zbGrid.zbGridlbVO[1].jybfNsjcybjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].jybfNsjcybjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].syslNsjcybjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].syslNsjcybjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].bqjnqjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].bqjnqjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].bqjnqjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].bqjnsqynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].bqjnsqynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].bqjnsqynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].bqjnsqynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].bqrkcbse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].bqrkcbse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].bqybtse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].bqybtse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].bqyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].bqyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].bqyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].bqyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ckkjzyjksyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].ajybfjsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].ajybfjsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].ajybfjsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ajybfjsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].fcyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].fcyjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].jxsezc\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].jxsezc\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].jxsezc\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].jxsezc\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].jxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].jxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].jxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].jxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].jybfYnse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].jybfYnse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].jybfYnse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].jybfYnse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].jzjtsjtse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].jzjtsjtse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].mdtytse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].mdtytse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].mslwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].mslwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].syslNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].syslNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].syslNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].syslNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].qcwjcbse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].qcwjcbse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].qcwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].qcwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].qcwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].qcwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].qmldse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].qmldse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].qmwjcbse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].qmwjcbse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].qmwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].qmwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].qmwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].qmwjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].mshwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].mshwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].jybfNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].jybfNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].jybfNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].jybfNsjctzxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].qmwjseQjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].qmwjseQjse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].yshwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].yshwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].yshwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].yshwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].sjdkse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].sjdkse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].sjdkse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].sjdkse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].mdtbfckxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].mdtbfckxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].msxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].msxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].sqldse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].sqldse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].ssckkjzyjkstse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ssckkjzyjkstse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].xxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].xxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].xxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].xxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].asysljsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].asysljsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].asysljsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].asysljsxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].ydksehj\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ydksehj\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].ynsehj\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].ynsehj\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].ynsehj\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ynsehj\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].ynsejze\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].ynsejze\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].ynsejze\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ynsejze\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].ynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].ynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].ynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].ynse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[3].yslwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[2].yslwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[1].yslwxse\']").val()',
                'return $("input[ng-model=\'zbGrid.zbGridlbVO[0].yslwxse\']").val()']

we_zzsbb = ['//*[@name="ajyjsbfjsdnsjcybjse_ybxm_bnlj"]', '//*[@name="ajyjsbfjsdnsjcybjse_ybxm_bys"]',
            '//*[@name="asysljsdnsjcybjse_ybxm_bnlj"]', '//*[@name="asysljsdnsjcybjse_ybxm_bys"]',
            '//*[@name="bqjnqjse_jzjtxm_bys"]', '//*[@name="bqjnqjse_ybxm_bnlj"]',
            '//*[@name="bqjnqjse_ybxm_bys"]', '//*[@name="bqjnsqynse_jzjtxm_bnlj"]',
            '//*[@name="bqjnsqynse_jzjtxm_bys"]', '//*[@name="bqjnsqynse_ybxm_bnlj"]',
            '//*[@name="bqjnsqynse_ybxm_bys"]', '//*[@name="bqrkcbse_ybxm_bnlj"]', '//*[@name="bqrkcbse_ybxm_bys"]',
            '//*[@name="bqybtse_jzjtxm_bys"]', '//*[@name="bqybtse_ybxm_bys"]', '//*[@name="bqyjse_jzjtxm_bnlj"]',
            '//*[@name="bqyjse_jzjtxm_bys"]', '//*[@name="bqyjse_ybxm_bnlj"]', '//*[@name="bqyjse_ybxm_bys"]',
            '//*[@name="ckkjzyjksyjse_ybxm_bys"]', '//*[@name="eajybfjsxse_jzjtxm_bnlj"]',
            '//*[@name="eajybfjsxse_jzjtxm_bys"]', '//*[@name="eajybfjsxse_ybxm_bnlj"]',
            '//*[@name="eajybfjsxse_ybxm_bys"]', '//*[@name="fcyjse_jzjtxm_bys"]', '//*[@name="fcyjse_ybxm_bys"]',
            '//*[@name="jxsezc_jzjtxm_bnlj"]', '//*[@name="jxsezc_jzjtxm_bys"]', '//*[@name="jxsezc_ybxm_bnlj"]',
            '//*[@name="jxsezc_ybxm_bys"]', '//*[@name="jxse_jzjtxm_bnlj"]', '//*[@name="jxse_jzjtxm_bys"]',
            '//*[@name="jxse_ybxm_bnlj"]', '//*[@name="jxse_ybxm_bys"]', '//*[@name="jyjsbfjsdynse_jzjtxm_bnlj"]',
            '//*[@name="jyjsbfjsdynse_jzjtxm_bys"]', '//*[@name="jyjsbfjsdynse_ybxm_bnlj"]',
            '//*[@name="jyjsbfjsdynse_ybxm_bys"]', '//*[@name="jzjtsjtse_jzjtxm_bnlj"]',
            '//*[@name="jzjtsjtse_jzjtxm_bys"]', '//*[@name="mdtytse_ybxm_bnlj"]', '//*[@name="mdtytse_ybxm_bys"]',
            '//*[@name="mslwxse_ybxm_bnlj"]', '//*[@name="mslwxse_ybxm_bys"]', '//*[@name="nsjcdzdxse_jzjtxm_bnlj"]',
            '//*[@name="nsjcdzdxse_jzjtxm_bys"]', '//*[@name="nsjcdzdxse_ybxm_bnlj"]',
            '//*[@name="nsjcdzdxse_ybxm_bys"]', '//*[@name="qcwjcbse_ybxm_bnlj"]', '//*[@name="qcwjcbse_ybxm_bys"]',
            '//*[@name="qcwjsedjwfs_jzjtxm_bnlj"]', '//*[@name="qcwjsedjwfs_jzjtxm_bys"]',
            '//*[@name="qcwjsedjwfs_ybxm_bnlj"]', '//*[@name="qcwjsedjwfs_ybxm_bys"]', '//*[@name="qmldse_jzjtxm_bys"]',
            '//*[@name="qmldse_ybxm_bys"]', '//*[@name="qmwjcbse_ybxm_bnlj"]', '//*[@name="qmwjcbse_ybxm_bys"]',
            '//*[@name="qmwjsedjwfs_jzjtxm_bnlj"]', '//*[@name="qmwjsedjwfs_jzjtxm_bys"]',
            '//*[@name="qmwjsedjwfs_ybxm_bnlj"]', '//*[@name="qmwjsedjwfs_ybxm_bys"]',
            '//*[@name="qzmshwxse_ybxm_bnlj"]', '//*[@name="qzmshwxse_ybxm_bys"]',
            '//*[@name="qznsjcdzdxse_jzjtxm_bnlj"]', '//*[@name="qznsjcdzdxse_jzjtxm_bys"]',
            '//*[@name="qznsjcdzdxse_ybxm_bnlj"]', '//*[@name="qznsjcdzdxse_ybxm_bys"]',
            '//*[@name="qzqjse_jzjtxm_bys"]', '//*[@name="qzqjse_ybxm_bys"]', '//*[@name="qzyshwxse_jzjtxm_bnlj"]',
            '//*[@name="qzyshwxse_jzjtxm_bys"]', '//*[@name="qzyshwxse_ybxm_bnlj"]', '//*[@name="qzyshwxse_ybxm_bys"]',
            '//*[@name="sjdkse_jzjtxm_bnlj"]', '//*[@name="sjdkse_jzjtxm_bys"]', '//*[@name="sjdkse_ybxm_bnlj"]',
            '//*[@name="sjdkse_ybxm_bys"]', '//*[@name="smdtbfckxse_ybxm_bnlj"]', '//*[@name="smdtbfckxse_ybxm_bys"]',
            '//*[@name="smsxse_ybxm_bnlj"]', '//*[@name="smsxse_ybxm_bys"]', '//*[@name="sqldse_jzjtxm_bys"]',
            '//*[@name="sqldse_ybxm_bys"]', '//*[@name="ssckkjzyjkstse_ybxm_bnlj"]',
            '//*[@name="ssckkjzyjkstse_ybxm_bys"]', '//*[@name="xxse_jzjtxm_bnlj"]', '//*[@name="xxse_jzjtxm_bys"]',
            '//*[@name="xxse_ybxm_bnlj"]', '//*[@name="xxse_ybxm_bys"]', '//*[@name="yasysljsxse_jzjtxm_bnlj"]',
            '//*[@name="yasysljsxse_jzjtxm_bys"]', '//*[@name="yasysljsxse_ybxm_bnlj"]',
            '//*[@name="yasysljsxse_ybxm_bys"]', '//*[@name="ydksehj_jzjtxm_bys"]', '//*[@name="ydksehj_ybxm_bys"]',
            '//*[@name="ynsehj_jzjtxm_bnlj"]', '//*[@name="ynsehj_jzjtxm_bys"]', '//*[@name="ynsehj_ybxm_bnlj"]',
            '//*[@name="ynsehj_ybxm_bys"]', '//*[@name="ynsejze_jzjtxm_bnlj"]', '//*[@name="ynsejze_jzjtxm_bys"]',
            '//*[@name="ynsejze_ybxm_bnlj"]', '//*[@name="ynsejze_ybxm_bys"]', '//*[@name="ynse_jzjtxm_bnlj"]',
            '//*[@name="ynse_jzjtxm_bys"]', '//*[@name="ynse_ybxm_bnlj"]', '//*[@name="ynse_ybxm_bys"]',
            '//*[@name="yslwxse_jzjtxm_bnlj"]', '//*[@name="yslwxse_jzjtxm_bys"]', '//*[@name="yslwxse_ybxm_bnlj"]',
            '//*[@name="yslwxse_ybxm_bys"]']

shuiju_fjsbb = []
